def ex2():
    print("Please note that this is the same as running []")
    print()
    squaredNumber = int(input("Type the number to be squared: "))
    print()
    print(squaredNumber * squaredNumber)
    print()
def ex3():
    print("Please note that this is the same as running {}")
    print()
    cubedNumber = int(input("Type the number to be cubed: "))
    print()
    print(cubedNumber * cubedNumber * cubedNumber)
    print()
def ex4():
    print()
    exponentedNumber = int(input("Type the number to be exponented: "))
    print()
    print(exponentedNumber * exponentedNumber * exponentedNumber * exponentedNumber)
    print()