def ex2():
    print()
    squaredNumber = int(input("Type the number to be squared: "))
    print()
    print(squaredNumber * squaredNumber)
    print()
def ex3():
    print("Please note that this is the same as running {}")
    print()
    cubedNumber = int(input("Type the number to be cubed: "))
    print()
    print(cubedNumber * cubedNumber * cubedNumber)
    print()
def ex4():
    print()
    exponentedNumber = int(input("Type the number to be exponented: "))
    print()
    print(exponentedNumber * exponentedNumber * exponentedNumber * exponentedNumber)
    print()
def ex5():
    print()
    num2Ex = input("Number to exponent?")
    print()
    print(num2Ex * num2Ex * num2Ex * num2Ex * num2Ex)
def ex1():
	print()
	num2Ex = input("Number to be exponented")
	print()
	print("Unbelievable!")
	print("I hope you're joking — you're asking this math: " +num2Use)
	print("There's not even any addition! The answer is " +num2Use)